# Generated by Django 4.2.5 on 2023-09-09 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 17, 47, 53, 323694)),
        ),
    ]
