# Generated by Django 4.2.4 on 2023-09-12 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0013_alter_new_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 16, 23, 42, 85753)),
        ),
    ]
