# Generated by Django 4.2.5 on 2023-09-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'user')], default=2),
        ),
    ]
