# Generated by Django 4.2.5 on 2023-09-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_roles_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='roles',
        ),
    ]
