# Generated by Django 4.2.4 on 2023-09-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murabbiylar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trenermodel',
            table='trener',
        ),
    ]
